FROM python:3.10-slim

# Install dependencies untuk OpenCV + multimedia
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libxext6 \
    ffmpeg \
    build-essential \
    wget \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy requirements dan install Torch (CPU only)
COPY requirements.txt .
RUN pip install --no-cache-dir torch==2.2.2 torchvision==0.17.2 --index-url https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir -r requirements.txt

# Download YOLO models
RUN wget -O yolo11n-pose.pt https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n-pose.pt && \
    wget -O yolo11s.pt https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11s.pt

# Copy semua file project
COPY . .

# Jalankan FastAPI pakai Uvicorn
CMD ["sh", "-c", "uvicorn app:app --host 0.0.0.0 --port ${PORT:-8000}"]
